name = "ChaosTools"
uuid = "608a59af-f2a3-5ad4-90b4-758bdf3122a7"
repo = "https://github.com/JuliaDynamics/ChaosTools.jl.git"
version = "1.25.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Entropies = "ed8fcbec-b94c-44b6-89df-898894ad9591"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LombScargle = "fc60dff9-86e7-5f2f-a8a0-edeadbb75bd9"
Neighborhood = "645ca80c-8b79-4109-87ea-e1f58159d116"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Combinatorics = "0.7, 1"
DelayEmbeddings = "1"
DSP = "0.6"
Distances = "0.7, 0.8, 0.9, 0.10"
Distributions = "0.21, 0.22, 0.23, 0.24"
DynamicalSystemsBase = "1.6.0"
Entropies = "0.11"
ForwardDiff = "0.8, 0.9, 0.10"
LombScargle = "0.4, 0.5, 1.0"
Neighborhood = "0.2.2"
OrdinaryDiffEq = "5"
Roots = "0.7, 0.8, 1.0"
StaticArrays = "0.11, 0.12.0, 1.0"
StatsBase = "0.24.0, 0.32, 0.33"
julia = "1.5"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "OrdinaryDiffEq", "Random"]
